name: Fixprostho
description: "Manage the students tests."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  pdf: ^3.10.1
  csv: ^5.0.0
  path_provider: ^2.0.11
  printing: ^5.6.0
  file_picker: ^4.5.1
  permission_handler: ^10.2.0
  flutter_image: ^4.1.11
  # firebase_core: ^2.4.1
  # flutter_bloc: ^8.1.1
  # hydrated_bloc: ^9.0.0
  # intl: ^0.17.0
  # path_provider: ^2.0.9
  # equatable: ^2.0.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - lib/screens/assets/  
  uses-material-design: true